const taskSchema = new mongoose.Schema({
  _id: { type: String, required: true, unique: true },
  title: { type: String, required: true, unique: true },
  description: { type: String, required: true },
  type: { type: String, required: true },
  priority: { type: String, required: true },
  color: { type: String, required: true },
  state: { type: String, required: true },
  startDate: { type: String, required: true },
  endDate: { type: String, required: true },
  lastModification: { type: String, required: true },
  emailNotification: { type: String, required: true },
  encharged: { type: String, required: true },
  createBy: { type: String, required: true },
  attachements: { type: String, required: true },
  comments: { type: String, required: true },
  tags: { type: String, required: true },
  projectId: { type: String, required: true },
  });